### ISSUE TITLE
Use int rather than "0" etc

### ISSUE THREAD

**Issue by verillious** [8leak/CYOAG#7]
https://github.com/8leak/CYOAG/blob/42d3f104f329660340d25efe5f4a3be9b55acdc5/game.py#L7

* if the IDs are numeric just use ints - maybe consider [UUIDS](https://docs.python.org/3/library/uuid.html) might be overkill

**Comment by 8leak** [comment]
Legacy from before using pydantic 
Closing this issue as resolved
