### ISSUE TITLE
Use lookup table (dict) for room-ids -> Room

### ISSUE THREAD

**Issue by verillious** [8leak/CYOAG#8]
https://github.com/8leak/CYOAG/blob/42d3f104f329660340d25efe5f4a3be9b55acdc5/game.py#L10

* this is kind of wasteful (in terms of processing), would be better to have a dict: ```{ 0: Room() }``` etc, then you could just do `rooms_dict[room_id]`
* or `{ name: Room() }` if that's what you need

**Comment by 8leak** [comment]
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/a27090c8-f5a7-4e9e-9944-005d2977bbb4">

Currently I store the Room objects in a list called ROOMS. Could i access the ids within those or just do away with the internal ID and use the dictionary key as the ID?

**Comment by verillious** [comment]
Replace ROOMS with a Dict

**Comment by 8leak** [comment]
Closing as issue resolved.
